 export const vistas = {
  adm_cartera_con_pagos :'vw_adm_cartera_libranza_con_pagos',
  pagos_con_cierre : 'vw_pagos_con_cierre',
  documentos_listado_productos_por_cierre : 'vw_documentos_listado_productos_por_cierre',
  corte_de_caja : 'vw_corte_de_caja',
  corte_de_caja_parcial : 'vw_corte_de_caja_parcial',
  corte_de_caja_pagos : 'vw_corte_de_caja_pagos',

  personas_disponibles_para_libranza : 'vw_personas_disponibles_para_libranza',
  personas_disponibles_para_usuarios : 'vw_personas_disponibles_para_usuarios',
  prd_product_con_existencia : 'vw_productos_con_existencia',
   aux_prd_product: 'vw_aux_prd_product',
  cajas : "vw_cajas" ,
  medios : "vw_medios" ,
  tiposDeDocumentos:'vw_tipos_de_documentos',
  mediosPorCajaActiva : "vw_medios_de_cajas_activas" ,
   categorias : "vw_categorias" ,
  cajasActivas : "vw_cajas_activas" ,
   ciudades : "vw_ciudades" ,
    departamento: "vw_departamento" ,
    maestros: "vw_maestros" ,
    tablasPorUsuario:'vw_tablas_usuarios',
    cajas_por_usuario :'vw_cajas_por_usuario',
    usuario : 'vw_usuario',
    establecimiento: 'vw_establecimiento',
    tipo_establecimiento: 'vw_tipo_establecimiento',
    documento: 'vw_obj_documentos',
    contadores:'vw_contadores',
    tipos_documentos_con_cont: 'vw_t_documentos_con_cont',
    domicilios:'vw_documentos_domicilio',
    auxCategoriasPrd:'vw_aux_prd_categorias',
   auxEstudioMarca : 'vw_prd_studio_marca_aux'
 }

