 export const vistas = {
  prd_product_con_existencia : 'vw_productos_con_existencia',
   aux_prd_product: 'vw_aux_prd_product',
  cajas : "vw_cajas" ,
  medios : "vw_medios" ,
  tiposDeDocumentos:'vw_tipos_de_documentos',
  mediosPorCajaActiva : "vw_medios_de_cajas_activas" ,
   categorias : "vw_categorias" ,
  cajasActivas : "vw_cajas_activas" ,
   ciudades : "vw_ciudades" ,
    departamento: "vw_departamento" ,
    maestros: "vw_maestros" ,
    tablasPorUsuario:'vw_tablas_usuarios',
    cajas_por_usuario :'vw_cajas_por_usuario',
    usuario : 'vw_usuario',
    establecimiento: 'vw_establecimiento',
    tipo_establecimiento: 'vw_tipo_establecimiento',
    documento: 'vw_obj_documentos',
    contadores:'vw_contadores',
    tipos_documentos_con_cont: 'vw_t_documentos_con_cont',
    domicilios:'vw_documentos_domicilio',
    auxCategoriasPrd:'vw_aux_prd_categorias',
   auxEstudioMarca : 'vw_prd_studio_marca_aux'
 }

