export interface Persona {
    "orden"?:number , 
"id"?:number , 
"name"?:string , 
"parent_id"?:number , 
"display_name"?:string , 
"company_type"?:string , 
"is_company"?:string , 
"email"?:string , 
"mobile"?:string , 
"phone"?:string , 
"type"?:string , 
"vat"?:string , 
"lang"?:string , 
"street"?:string , 
"city"?:string , 
"street2"?:string , 
"state_id"?:string , 
"zip"?:string , 
"country_id"?:string , 
"function"?:string , 
"category_id"?:string , 
"title"?:string , 
"l10n_latam_identification_type_id"?:string , 
"nombre_pais"?:string , 
"nombre_estado"?:string , 
"active"?:string   
}
